### ISSUE TITLE
Consider adding vendor page URI to the JSON

### ISSUE THREAD

**Issue by tfpauly** [capport-wg/api#20]
We should look at adding to the base API document a JSON key to specify a URI for a vendor info page (store info, maps, entertainment, etc)

**Comment by ekline** [comment]
Is vendor the right name here?  That kinda sounds like it's a Cisco or Aruba -inspired web page.

Did "venue-info-url" or "network-specific-info-url" get evaluated and rejected already?

**Comment by darshakthakore** [comment]
if you prefer a better name, suggest away. I just put it to start with. We wanted to make it somewhat generic like in case of an airplane wifi, it would be the status page for your flight/entertainment etc. 
If folks like "venue-info-url" better, we'll do that.
