### ISSUE TITLE
Define a mechanism for organization-specific extension

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/api#23]
Should we define an IANA registry for adding new keys?

**Comment by tfpauly** [comment]
Yes, yes we should.

**Comment by darshakthakore** [comment]
and i already commented in the PR,  but if possible it would be beneficial to have some distinction between IETF or a relevant organization (like WFA, WBA) requested keys vs from some individual organization

**Comment by tfpauly** [comment]
Would we want to suggest having a nested dictionary format for organization-specific extensions? Like "wba" as a key to a dictionary; or a sub-dictionary indicating that there are WISPr-related settings to be aware of?

**Comment by darshakthakore** [comment]
i think it would be a good idea. We have seen WBA start to take active interest in the documents. Also there's work happening in WFA that could benefit from having an extension point

**Comment by martinthomson** [comment]
RFC 6648 might suggest otherwise. If there are things that a group wants to add that are truly unique to that group, this is probably fine.

**Comment by tfpauly** [comment]
Yes, I think that more than having per-group keys (with almost certain overlap), I'd imagine that compatibility with certain technologies would be handled via these sub-dictionaries, such as what I mentioned for WISPr. Not sure how critical mentioning this is in the document though.

**Comment by martinthomson** [comment]
Can we call this one done?

**Comment by darshakthakore** [comment]
I'm assuming we will go down the path of defining an IANA registry with access technology specific extension ?

**Comment by tfpauly** [comment]
The description in "Captive Portal API Keys Registry" gives some guidance for prefixes, etc. I assume the experts once designated can work with WFA/WBA to define proper entries.
