### ISSUE TITLE
suggest renaming vendor-info-url to location- or venue-

### ISSUE THREAD

**Issue by wlanmac** [capport-wg/api#25]
'vendor' can mean lots of things ... e.g. Cisco or Ruckus.

**Comment by ekline** [comment]
This is a good point.  vendor-url-info sounds like it might point to a web page about the portal vendor (operator) or the vendor of the network gear used by the enforcement point.

Not to start a bikeshed, but +1 to "venue-info-url".

**Comment by tfpauly** [comment]
Switched to venue-information-url in 966a348c1f853a022b565ade66eb29fbb0cdab6b
