### ISSUE TITLE
Be more precise about bytes remaining

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/api#28]
We identified a need to be clearer here that the value counted as both up and down (added together) and that we needed to explicitly say that the count includes the IP packet header.

**Comment by tfpauly** [comment]
The current text is this:

```
- "bytes-remaining" (optional, integer): indicates the number of bytes remaining, after which the
client will be in placed into a captive state. The byte count represents the total number of IP packet
(layer 3) bytes sent and received by the client. Captive portal systems might not count traffic to
whitelisted servers, such as the API server, but clients cannot rely on such behavior.
```

Is there something better you recommend?

**Comment by tfpauly** [comment]
I think we can close this based on recent updates/clarifications.
