### ISSUE TITLE
How does the server identify the user?

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/api#34]
I know there has been a lot of discussion about User Equipment Identity, and I'm not sure what the conclusions are, but I think this API document needs to explain how it must work.

**Comment by tfpauly** [comment]
Yes, and we should reference the architecture section 3 on this.

**Comment by tfpauly** [comment]
Added via https://github.com/capport-wg/api/commit/477e7cc1c2f82c68e221c466b9ac44548e238fc0
