### ISSUE TITLE
The example should say HTTPS vs HTTP

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/api#35]
ORIGINAL:
"... a client sends an HTTP GET request."

PROPOSED:
"... a client sends an HTTPS GET request."

**Comment by tfpauly** [comment]
Not sure this is the right thing to do. A GET request is part of the HTTP protocol, which is the same whether you run it over TLS or not. https is a different scheme, and we do require running on TLS, but for specifying the content of requests and responses, I’d rather just refer to HTTP. 

Thoughts?

**Comment by dcdolson** [comment]
I buy that. Because elsewhere I think it says the encryption is required I assumed this was an oversight.

**Comment by tfpauly** [comment]
Okay, if it's okay I'll close this one out.
