### ISSUE TITLE
HMAC key

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/api#4]
Should we hold the addition of this until we have something that depends on it being in the API?

**Comment by tfpauly** [comment]
We certainly can, although if we want to use a key as discussed in the WG meeting for the purposes of ICMP validation, having a way to add a key here is nice for removing a bootstrapping step. Hopefully we can get an updated ICMP document out with the API document, and they can reference one another in this way.

**Comment by martinthomson** [comment]
Discussed in London, remove this.
