### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/api#8]
To meet the architecture requirements.

**Comment by martinthomson** [comment]
Note that, based on discussion, we need to mandate OCSP stapling and prohibit relying on AIA.  I can provide details as needed.

**Comment by martinthomson** [comment]
See [DOH](https://github.com/dohwg/draft-ietf-doh-dns-over-https/blob/master/draft-ietf-doh-dns-over-https-latest.mkd#operational-considerations) for text.

**Comment by tfpauly** [comment]
I think we should fold this issue in with #7, since we'll probably only want one set of text describing OCSP requirements, etc.
